default_stages: [commit, push]

repos:
- repo: local
  hooks:
  - id: test
    name: Run all tests
    entry: make test
    language: system
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: trailing-whitespace
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.4.0
  hooks:
  - id: editorconfig-checker
    alias: ec
